apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: job-service=aseongjun/job-service
    argocd-image-updater.argoproj.io/user-service.update-strategy: newest-build
    argocd-image-updater.argoproj.io/user-service.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/user-service.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aseongjun99/devops-demo
    targetRevision: HEAD
    path: helm-chart/job-service
  destination:
    server: https://kubernetes.default.svc
    namespace: job-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
