#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: scheduler-service
#  namespace: argocd
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/aseongjun99/devops-demo
#    targetRevision: HEAD
#    path: helm-chart/scheduler-service  # Chart.yaml 있는 위치
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: scheduler-service
#  syncPolicy:
#    automated:
#      prune: true       # 불필요한 리소스 제거
#      selfHeal: true    # 드리프트 수정

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scheduler-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: scheduler-service=aseongjun/scheduler-service
    argocd-image-updater.argoproj.io/scheduler-service.update-strategy: newest-build
    argocd-image-updater.argoproj.io/scheduler-service.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/scheduler-service.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aseongjun99/devops-demo
    targetRevision: HEAD
    path: helm-chart/scheduler-service
  destination:
    server: https://kubernetes.default.svc
    namespace: scheduler-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
